name: .NET Core Publish Package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Run tests
      run: dotnet test
    - name: Package nuget package
      run: dotnet build --configuration Release --output artifacts src/Microsoft.AspNetCore.Identity.MongoDB/Microsoft.AspNetCore.Identity.MongoDB.csproj
    - name: Publish nuget package
      run: dotnet nuget push "artifacts/*.nupkg" --source "github"
